In [94]:
import statsmodels as stat
import seaborn as sbn
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import normalize


In [95]:
dtst = pd.read_csv('C:/Datascience/credit_immo.csv')

In [96]:
print(dtst.shape)

(19, 10)


In [97]:
print(dtst.describe())

       Niv_Etude_Bac        age        Salaire  dette_anterieure     apport  \
count      18.000000  19.000000      19.000000         19.000000  19.000000   
mean        1.444444  36.947368   43331.578947      11890.526316   0.142105   
std         2.812205  11.824991   21473.499240      23687.941957   0.130451   
min        -3.000000  23.000000   15000.000000          0.000000   0.000000   
25%         0.000000  28.500000   28500.000000       1260.000000   0.000000   
50%         0.500000  37.000000   40000.000000       3000.000000   0.100000   
75%         3.000000  41.500000   47900.000000       8000.000000   0.250000   
max         8.000000  70.000000  100000.000000     100000.000000   0.400000   

       enfant_a_Charge  
count        18.000000  
mean          1.333333  
std           1.328422  
min           0.000000  
25%           0.000000  
50%           1.000000  
75%           2.000000  
max           4.000000  


In [98]:
print(dtst.columns)

Index(['ID_NOM', 'Niv_Etude_Bac', 'age', 'contrat_de_travail', 'Salaire',
       'dette_anterieure', 'etat_civile', 'apport', 'enfant_a_Charge',
       'Solvable'],
      dtype='object')


In [99]:
x = dtst.iloc[:,-9:-1].values

In [100]:
print(x)

[[3.0 45 'CDI' 40000 4000 'M' 0.3 3.0]
 [5.0 28 'CDI' 30500 1320 'M' 0.1 0.0]
 [0.0 55 'CDI' 28000 40000 'C' 0.0 0.0]
 [4.0 23 'CDD' 15000 0 'M' 0.1 nan]
 [0.0 33 'CDD' 27000 3000 'C' 0.1 2.0]
 [0.0 41 'INTERIM' 40000 1000 'M' 0.0 4.0]
 [-1.0 29 'CDI' 50000 3000 'C' 0.0 0.0]
 [-3.0 24 'INTERIM' 29000 5000 'C' 0.0 0.0]
 [nan 26 'CDI' 44000 0 'M' 0.1 1.0]
 [3.0 37 'CDI' 45800 2000 'M' 0.2 2.0]
 [2.0 40 'CDI' 60000 1500 'M' 0.3 3.0]
 [0.0 38 'CDD' 26000 8000 'C' 0.4 0.0]
 [-3.0 39 'INTERIM' 29000 4900 'M' 0.0 1.0]
 [0.0 31 'CDI' 43000 100000 'M' 0.2 2.0]
 [1.0 70 'CDD' 45000 17000 'C' 0.3 0.0]
 [0.0 42 'ENTRPRENEUR' 70000 26000 'M' 0.2 0.0]
 [8.0 46 'CDI' 80000 8000 'M' 0.0 3.0]
 [3.0 23 'CDI' 100000 0 'M' 0.3 1.0]
 [4.0 32 'CDI' 21000 1200 'M' 0.1 2.0]]


In [101]:
y = dtst.iloc[:,-1].values

In [102]:
print(y)

['OUI' 'OUI' 'NON' 'OUI' 'NON' 'NON' 'NON' 'NON' 'OUI' 'OUI' 'OUI' 'NON'
 'NON' 'NON' 'NON' 'NON' 'OUI' 'OUI' 'OUI']


In [103]:
print(dtst.isnull().sum)

<bound method DataFrame.sum of     ID_NOM  Niv_Etude_Bac    age  contrat_de_travail  Salaire  \
0    False          False  False               False    False   
1    False          False  False               False    False   
2    False          False  False               False    False   
3    False          False  False               False    False   
4    False          False  False               False    False   
5    False          False  False               False    False   
6    False          False  False               False    False   
7    False          False  False               False    False   
8    False           True  False               False    False   
9    False          False  False               False    False   
10   False          False  False               False    False   
11   False          False  False               False    False   
12   False          False  False               False    False   
13   False          False  False               False    Fal

In [104]:
conda install scikit-learn=0.19

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [105]:
imptr = Imputer(missing_values='NaN',strategy = 'mean',axis = 0)

In [106]:
imptr.fit(x[:,0:1])
imptr.fit(x[:,7:8])

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [107]:
x[:,0:1] = imptr.transform(x[:,0:1])
# toutes les valeurs manquantes dans x
x[:,7:8] = imptr.transform(x[:,7:8])

In [108]:
print(x)

[[3.0 45 'CDI' 40000 4000 'M' 0.3 3.0]
 [5.0 28 'CDI' 30500 1320 'M' 0.1 0.0]
 [0.0 55 'CDI' 28000 40000 'C' 0.0 0.0]
 [4.0 23 'CDD' 15000 0 'M' 0.1 1.3333333333333333]
 [0.0 33 'CDD' 27000 3000 'C' 0.1 2.0]
 [0.0 41 'INTERIM' 40000 1000 'M' 0.0 4.0]
 [-1.0 29 'CDI' 50000 3000 'C' 0.0 0.0]
 [-3.0 24 'INTERIM' 29000 5000 'C' 0.0 0.0]
 [1.3333333333333333 26 'CDI' 44000 0 'M' 0.1 1.0]
 [3.0 37 'CDI' 45800 2000 'M' 0.2 2.0]
 [2.0 40 'CDI' 60000 1500 'M' 0.3 3.0]
 [0.0 38 'CDD' 26000 8000 'C' 0.4 0.0]
 [-3.0 39 'INTERIM' 29000 4900 'M' 0.0 1.0]
 [0.0 31 'CDI' 43000 100000 'M' 0.2 2.0]
 [1.0 70 'CDD' 45000 17000 'C' 0.3 0.0]
 [0.0 42 'ENTRPRENEUR' 70000 26000 'M' 0.2 0.0]
 [8.0 46 'CDI' 80000 8000 'M' 0.0 3.0]
 [3.0 23 'CDI' 100000 0 'M' 0.3 1.0]
 [4.0 32 'CDI' 21000 1200 'M' 0.1 2.0]]


In [109]:
print(y)

['OUI' 'OUI' 'NON' 'OUI' 'NON' 'NON' 'NON' 'NON' 'OUI' 'OUI' 'OUI' 'NON'
 'NON' 'NON' 'NON' 'NON' 'OUI' 'OUI' 'OUI']


In [110]:
#Labeliser le donnees numeriques
labEncr_x = LabelEncoder()
x[:,2] = labEncr_x.fit_transform(x[:,2])
x[:,5] =labEncr_x.fit_transform(x[:,5])

In [111]:
print(x)

[[3.0 45 1 40000 4000 1 0.3 3.0]
 [5.0 28 1 30500 1320 1 0.1 0.0]
 [0.0 55 1 28000 40000 0 0.0 0.0]
 [4.0 23 0 15000 0 1 0.1 1.3333333333333333]
 [0.0 33 0 27000 3000 0 0.1 2.0]
 [0.0 41 3 40000 1000 1 0.0 4.0]
 [-1.0 29 1 50000 3000 0 0.0 0.0]
 [-3.0 24 3 29000 5000 0 0.0 0.0]
 [1.3333333333333333 26 1 44000 0 1 0.1 1.0]
 [3.0 37 1 45800 2000 1 0.2 2.0]
 [2.0 40 1 60000 1500 1 0.3 3.0]
 [0.0 38 0 26000 8000 0 0.4 0.0]
 [-3.0 39 3 29000 4900 1 0.0 1.0]
 [0.0 31 1 43000 100000 1 0.2 2.0]
 [1.0 70 0 45000 17000 0 0.3 0.0]
 [0.0 42 2 70000 26000 1 0.2 0.0]
 [8.0 46 1 80000 8000 1 0.0 3.0]
 [3.0 23 1 100000 0 1 0.3 1.0]
 [4.0 32 1 21000 1200 1 0.1 2.0]]


In [112]:
onehotEncr = OneHotEncoder(categorical_features=[2])
oneHotEncr = OneHotEncoder(categorical_features=[5])

In [113]:
print(x)

[[3.0 45 1 40000 4000 1 0.3 3.0]
 [5.0 28 1 30500 1320 1 0.1 0.0]
 [0.0 55 1 28000 40000 0 0.0 0.0]
 [4.0 23 0 15000 0 1 0.1 1.3333333333333333]
 [0.0 33 0 27000 3000 0 0.1 2.0]
 [0.0 41 3 40000 1000 1 0.0 4.0]
 [-1.0 29 1 50000 3000 0 0.0 0.0]
 [-3.0 24 3 29000 5000 0 0.0 0.0]
 [1.3333333333333333 26 1 44000 0 1 0.1 1.0]
 [3.0 37 1 45800 2000 1 0.2 2.0]
 [2.0 40 1 60000 1500 1 0.3 3.0]
 [0.0 38 0 26000 8000 0 0.4 0.0]
 [-3.0 39 3 29000 4900 1 0.0 1.0]
 [0.0 31 1 43000 100000 1 0.2 2.0]
 [1.0 70 0 45000 17000 0 0.3 0.0]
 [0.0 42 2 70000 26000 1 0.2 0.0]
 [8.0 46 1 80000 8000 1 0.0 3.0]
 [3.0 23 1 100000 0 1 0.3 1.0]
 [4.0 32 1 21000 1200 1 0.1 2.0]]


In [114]:
#on transforme les donnees de onhotencoder en tableau
x = onehotEncr.fit_transform(x).toarray()

In [115]:
labEncr_y = LabelEncoder()
y = labEncr_y.fit_transform(y)

In [116]:
print(x)

[[ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   3.00000000e+00  4.50000000e+01  4.00000000e+04  4.00000000e+03
   1.00000000e+00  3.00000000e-01  3.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   5.00000000e+00  2.80000000e+01  3.05000000e+04  1.32000000e+03
   1.00000000e+00  1.00000000e-01  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  5.50000000e+01  2.80000000e+04  4.00000000e+04
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   4.00000000e+00  2.30000000e+01  1.50000000e+04  0.00000000e+00
   1.00000000e+00  1.00000000e-01  1.33333333e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  3.30000000e+01  2.70000000e+04  3.00000000e+03
   0.00000000e+00  1.00000000e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  

In [117]:
# application de cross_validation de scikitlearn to shrink the data in train and test data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [118]:
#Standardidation(centrer-reduir signifie conversion vers un stadard commun)
#stdSc = StandardScaler()

#x_train = stdSc.fit_transform(x_train)
#x_test = stdSc.fit_transform(x_test)

In [123]:
#print(x_train)

In [120]:
#print(x_test)

In [124]:
#La normalisation des donnees si on a des colonnes avec de gros nombre et d'autres avec de petit nombres

x_train = normalize(x_train)
x_test = normalize(x_test)

In [125]:
print(x_train)

[[ 2.07882467e-05  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.07882467e-05  1.45517727e-03  9.35471103e-01  3.53400194e-01
   0.00000000e+00  6.23647402e-06  0.00000000e+00]
 [ 0.00000000e+00  1.24379628e-05  0.00000000e+00  0.00000000e+00
   9.95037022e-05  5.72146287e-04  9.95037022e-01  9.95037022e-02
   1.24379628e-05  0.00000000e+00  3.73138883e-05]
 [ 0.00000000e+00  1.99640936e-05  0.00000000e+00  0.00000000e+00
  -1.99640936e-05  5.78958713e-04  9.98204678e-01  5.98922807e-02
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.68104814e-05  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.21474589e-03  9.93882998e-01  1.10431444e-01
   0.00000000e+00  3.68104814e-06  7.36209628e-05]
 [ 0.00000000e+00  2.04807850e-05  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.12644318e-03  5.73461980e-01  8.19231401e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.49921779e-05
   0.00000000e+00  

In [126]:
print(x_test)

[[0.00000000e+00 1.66614570e-05 0.00000000e+00 0.00000000e+00
  3.33229141e-05 6.66458282e-04 9.99687422e-01 2.49921856e-02
  1.66614570e-05 4.99843711e-06 4.99843711e-05]
 [0.00000000e+00 3.27562084e-05 0.00000000e+00 0.00000000e+00
  1.63781042e-04 9.17173835e-04 9.99064356e-01 4.32381951e-02
  3.27562084e-05 3.27562084e-06 0.00000000e+00]
 [0.00000000e+00 2.27272687e-05 0.00000000e+00 0.00000000e+00
  3.03030250e-05 5.90908987e-04 9.99999824e-01 0.00000000e+00
  2.27272687e-05 2.27272687e-06 2.27272687e-05]
 [0.00000000e+00 4.75414359e-05 0.00000000e+00 0.00000000e+00
  1.90165744e-04 1.52132595e-03 9.98370154e-01 5.70497231e-02
  4.75414359e-05 4.75414359e-06 9.50828718e-05]]
